Add charter and initial WG members
ContainerSSH/community pull request #1
Opened 2022-06-05 13:40 UTC by sanjacodes

## Changes introduced with this PR

This PR adds the confirmed initial working group members, a charter, a template for decision proposals, and the record file.

Please add comments if you have any suggestions, request changes, if you'd like changes to the number of chairs or if you'd like to be added as a chair (@tsipinakis) or founding member of the Working Group (everyone else who is reading this PR).

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/ContainerSSH/community/blob/main/CONTRIBUTING.md).

2022-06-05 13:57 UTC, janosdebugs requested changes
I think the WG membership criteria should be explicit.

2022-06-05 13:57 UTC, janosdebugs commented on CHARTER.md
> +* Any individual who wants to join and passes a review of their PR sent to [WG_MEMBERS.md](WG_MEMBERS.md))
I would suggest making the membership criteria more explicit:

To join the working group, you must be one of the following:

- an active user of ContainerSSH (end user, product builder, researcher, etc; please describe your use case in the PR)
- actively helping community members on any of the official ContainerSSH channels
- make code, documentation, or artwork contributions to ContainerSSH

2022-06-05 15:51 UTC, janosdebugs approved these changes

2022-06-06 14:12 UTC, bencurio approved these changes

2022-06-06 18:35 UTC, tsipinakis commented on WG_MEMBERS.md
> +
> if you'd like to be added as a chair (@tsipinakis)

Yes, I'd like to actively participate in this project so add me please. :)

```suggestion
* [Nikos Tsipinakis](https://github.com/tsipinakis)

```

2022-06-07 07:20 UTC, tsipinakis approved these changes

2022-06-07 07:20 UTC, tsipinakis commented on CHARTER.md
> +* 3 chairs with equal rights who
```suggestion
* 4 chairs with equal rights who
```

2022-06-07 07:42 UTC, janosdebugs approved these changes

2022-06-07 07:43 UTC, janosdebugs commented
@tsipinakis @bencurio final review please!

2022-06-07 07:45 UTC, bencurio approved these changes

2022-06-07 07:49 UTC, tsipinakis approved these changes

2022-06-07 09:39 UTC, sanjacodes commented
Congratulations, ContainerSSH! 🎉

2022-06-07 09:39 UTC, merged